CREATE TABLE IF NOT EXISTS `company_supplier` (
  `id` int NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `createTime` varchar(32) DEFAULT NULL COMMENT '创建时间',
  `updateTime` varchar(32) DEFAULT NULL COMMENT '更新时间',
  `tenantId` int DEFAULT NULL COMMENT '租户ID',
  `supplierName` varchar(200) NOT NULL COMMENT '供应商名称',
  `supplierType` varchar(20) NOT NULL DEFAULT 'temporary' COMMENT '供应商类型：temporary/formal',
  `supplierSource` varchar(50) NOT NULL COMMENT '供应商来源',
  `remark` text COMMENT '备注',
  `contactName` varchar(100) NOT NULL COMMENT '联系人',
  `contactInfo` varchar(200) NOT NULL COMMENT '联系方式',
  `infoStatus` varchar(20) NOT NULL DEFAULT 'active' COMMENT '信息状态：active/pending/dormant',
  `manageStatus` varchar(20) NOT NULL DEFAULT 'valid' COMMENT '管理状态：valid/invalid',
  `supplierNature` varchar(50) DEFAULT NULL COMMENT '供应商性质',
  `businessCategory` json DEFAULT NULL COMMENT '业务类别',
  `paymentTerm` int DEFAULT NULL COMMENT '账期天数',
  `cooperationRelation` varchar(20) DEFAULT NULL COMMENT '合作关系：good/normal/bad',
  `aiBackgroundCheck` text COMMENT 'AI背调',
  `aiSupplierProfile` text COMMENT 'AI供应商画像',
  `invalidReason` text COMMENT '失效原因',
  `quoteStartTime` datetime DEFAULT NULL COMMENT '首次报价时间',
  `lastQuoteTime` datetime DEFAULT NULL COMMENT '最近报价时间',
  `createUserId` int DEFAULT NULL COMMENT '创建人ID',
  `lastEditUserId` int DEFAULT NULL COMMENT '最后编辑人ID',
  PRIMARY KEY (`id`),
  KEY `IDX_company_supplier_createTime` (`createTime`),
  KEY `IDX_company_supplier_updateTime` (`updateTime`),
  KEY `IDX_company_supplier_tenantId` (`tenantId`),
  KEY `IDX_company_supplier_name` (`supplierName`),
  KEY `IDX_company_supplier_type` (`supplierType`),
  KEY `IDX_company_supplier_source` (`supplierSource`),
  KEY `IDX_company_supplier_info_status` (`infoStatus`),
  KEY `IDX_company_supplier_manage_status` (`manageStatus`),
  KEY `IDX_company_supplier_relation` (`cooperationRelation`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='供应商管理';
