CREATE TABLE IF NOT EXISTS `company_purchase_contract` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `createTime` varchar(255) NOT NULL COMMENT '创建时间',
  `updateTime` varchar(255) NOT NULL COMMENT '更新时间',
  `tenantId` bigint DEFAULT NULL COMMENT '租户ID',
  `contractNo` varchar(80) NOT NULL COMMENT '采购合同号',
  `orderNo` varchar(80) NOT NULL COMMENT '合同订单号',
  `supplierId` bigint NOT NULL COMMENT '供应商ID',
  `supplierName` varchar(200) NOT NULL COMMENT '供应商名称',
  `supplierType` varchar(20) NOT NULL COMMENT '供应商类型 temporary/formal',
  `purchaseAmount` decimal(14,2) NOT NULL DEFAULT '0.00' COMMENT '采购金额',
  `orderDate` date NOT NULL COMMENT '下单日期',
  `expectedArrivalDate` date NOT NULL COMMENT '预计到货日期',
  `attachments` json DEFAULT NULL COMMENT '合同附件',
  `remark` text COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_company_purchase_contract_contract_no` (`contractNo`),
  UNIQUE KEY `uk_company_purchase_contract_order_no` (`orderNo`),
  KEY `idx_company_purchase_contract_create_time` (`createTime`),
  KEY `idx_company_purchase_contract_supplier_id` (`supplierId`),
  KEY `idx_company_purchase_contract_supplier_name` (`supplierName`),
  KEY `idx_company_purchase_contract_supplier_type` (`supplierType`),
  KEY `idx_company_purchase_contract_order_date` (`orderDate`),
  KEY `idx_company_purchase_contract_expected_arrival_date` (`expectedArrivalDate`),
  KEY `idx_company_purchase_contract_tenant_id` (`tenantId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='采购合同';

CREATE TABLE IF NOT EXISTS `company_purchase_contract_product` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `createTime` varchar(255) NOT NULL COMMENT '创建时间',
  `updateTime` varchar(255) NOT NULL COMMENT '更新时间',
  `tenantId` bigint DEFAULT NULL COMMENT '租户ID',
  `contractId` bigint NOT NULL COMMENT '采购合同ID',
  `quoteId` bigint DEFAULT NULL COMMENT '报价单ID',
  `quoteProductId` varchar(100) DEFAULT NULL COMMENT '报价产品ID',
  `inquiryId` bigint DEFAULT NULL COMMENT '询价单ID',
  `productId` bigint DEFAULT NULL COMMENT '产品ID',
  `productName` varchar(200) NOT NULL COMMENT '产品名称',
  `brand` varchar(100) DEFAULT NULL COMMENT '品牌',
  `model` varchar(150) DEFAULT NULL COMMENT '型号',
  `quality` varchar(100) DEFAULT NULL COMMENT '质量',
  `purchasePrice` decimal(14,2) NOT NULL COMMENT '采购价格',
  `purchaseQuantity` decimal(14,4) NOT NULL COMMENT '采购数量',
  `pendingPurchaseQuantity` decimal(14,4) DEFAULT NULL COMMENT '待采购数量',
  `purchasedQuantity` decimal(14,4) DEFAULT NULL COMMENT '已采购数量',
  `amount` decimal(14,2) NOT NULL COMMENT '小计金额',
  `remark` text COMMENT '备注',
  PRIMARY KEY (`id`),
  KEY `idx_company_purchase_contract_product_create_time` (`createTime`),
  KEY `idx_company_purchase_contract_product_contract_id` (`contractId`),
  KEY `idx_company_purchase_contract_product_quote_id` (`quoteId`),
  KEY `idx_company_purchase_contract_product_inquiry_id` (`inquiryId`),
  KEY `idx_company_purchase_contract_product_product_id` (`productId`),
  KEY `idx_company_purchase_contract_product_product_name` (`productName`),
  KEY `idx_company_purchase_contract_product_tenant_id` (`tenantId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='采购合同产品明细';
